# preload = ~/documents/images/godfather.jpg
# wallpaper = eDP-1, ~/documents/images/godfather.jpg
# wallpaper = HDMI-A-1, ~/documents/images/godfather.jpg

wallpaper {
  monitor = eDP-1
  path = ~/documents/images/godfather.jpg
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = ~/documents/images/godfather.jpg
  fit_mode = cover
}
